#66 รายการ mapping ให้มีตัวกรอง (ยา,มิใช่ยา,ยาผลิต) (staffและadmin)
mophos/mmis-inventory-frontend pull request #83
Opened 2018-03-21 16:02 UTC by beerIT15kmutnb

#66 รายการ mapping ให้มีตัวกรอง (ยา,มิใช่ยา,ยาผลิต) (staffและadmin)

2018-03-21 16:42 UTC, siteslave requested changes

2018-03-21 16:42 UTC, siteslave commented on src/app/admin/his-issue-transaction/his-issue-transaction.component.ts
> +        this.genericTypes = rs.rows;
ตัวนี้ควรจะแสดงเฉพาะรายการที่เขามีสิทธิดูได้นะ เช่นอาจจะมีเฉพาะยา หรือ เวชภัณฑ์มิใช่ยา แต่ไม่สามารถดูยาผลิตได้

2018-03-21 16:51 UTC, beerIT15kmutnb commented
Get type ตามสิทธิ์ไว้ครับ

รับ Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Satit Rianpit <notifications@github.com>
Sent: Wednesday, March 21, 2018 11:42:06 PM
To: mophos/mmis-inventory-frontend
Cc: Beer_Nawaphol; Author
Subject: Re: [mophos/mmis-inventory-frontend] #66 รายการ mapping ให้มีตัวกรอง (ยา,มิใช่ยา,ยาผลิต) (staffและadmin) (#83)


@siteslave requested changes on this pull request.

________________________________

In src/app/admin/his-issue-transaction/his-issue-transaction.component.ts<https://github.com/mophos/mmis-inventory-frontend/pull/83#discussion_r176153504>:

> @@ -30,13 +35,43 @@ export class HisIssueTransactionComponent implements OnInit {
   }

   ngOnInit() {
-    this.getTransactionList();
+    this.getGenericType();
+    // this.getTransactionList();
+  }
+
+  async getGenericType() {
+    try {
+      const rs = await this.hisTransactionService.getGenericType();
+
+      if (rs.ok) {
+        this.genericTypes = rs.rows;


ตัวนี้ควรจะแสดงเฉพาะรายการที่เขามีสิทธิดูได้นะ เช่นอาจจะมีเฉพาะยา หรือ เวชภัณฑ์มิใช่ยา แต่ไม่สามารถดูยาผลิตได้

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/mophos/mmis-inventory-frontend/pull/83#pullrequestreview-105807204>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ARMrGGVwi76r2VXsmTSpSQXlqqu0m6vFks5tgoLegaJpZM4S0f2A>.

2018-03-22 02:35 UTC, siteslave approved these changes

2018-03-22 02:36 UTC, siteslave commented
https://github.com/beerIT15kmutnb/mmis-inventory-backend/blob/ea7cc3bc3af8337255d3539ea79deab86286146e/src/routes/generics.ts#L17-L21

2018-03-22 04:08 UTC, merged